### ISSUE TITLE
语言标识能改成chi就好了。

### ISSUE THREAD

**Issue by serenity666** [caryyu/jellyfin-plugin-maxsubtitle#1]
下载后字幕后缀被命名为maxsubtitle，能改成chi就好了。这样方便系统自动选择
![Screenshot_2021-12-08-03-55-25-205_org jellyfin mobile](https://user-images.githubusercontent.com/64485323/145097087-12fe6cc7-1a87-4e4d-8698-76f7ab74874d.jpg)
![Screenshot_2021-12-08-03-54-59-774_org jellyfin mobile](https://user-images.githubusercontent.com/64485323/145097094-dbea7335-19cd-4444-a8e1-64d625d8ee15.jpg)

**Comment by caryyu** [comment]
@serenity666 谢谢告知，我真没发现还有这个默认设置功能 :)

**Comment by caryyu** [comment]
@serenity666 已经修复了，更新 0.0.2 版本再试试。
