### ISSUE TITLE
Jellyfin 10.8 兼容问题

### ISSUE THREAD

**Issue by fallenyy** [caryyu/jellyfin-plugin-maxsubtitle#3]
在 jellyfin10.8 中，插件配置无法保存，手动修改Jellyfin.Plugin.MaxSubtitle.xml后依然无法使用。不确定是jellyfin的问题还是插件不兼容，opendouban也无法使用。。。。

**Comment by caryyu** [comment]
@fallenyy 你好，感谢你的反馈，由于 10.8 的 Release 较新并做了大量的变更，我建议追求稳定的话暂时降级到 10.7 来使用，同时 10.8 的兼容我也会陆续做一些尝试，谢谢你的支持。

**Comment by caryyu** [comment]
@fallenyy 目前插件版本 2.0.0 已经做了兼容支持。

**Comment by fallenyy** [comment]
太棒了，感谢作者。。。。已经第一时间用上了。测试没问题。

**Comment by caryyu** [comment]
我先关闭该 Issue 了，有任何问题再重开，谢谢。
