### ISSUE TITLE
为什么我测试无论是电影还是剧集，都无法搜索到字幕？

### ISSUE THREAD

**Issue by hisune** [caryyu/jellyfin-plugin-maxsubtitle#4]
测试了很多电影和剧集都无法搜索到字幕

搜索结果：
![1](https://user-images.githubusercontent.com/7941669/158512195-a3ab88ce-db58-4314-b758-f1eec8456255.png)

插件状态：
![2](https://user-images.githubusercontent.com/7941669/158512200-2274c597-6354-4a55-ae72-abb01ac48bca.png)

jellyfin版本：10.8.0

**Comment by hisune** [comment]
并且你的插件安装后就无法禁用，或者卸载了

**Comment by caryyu** [comment]
@hisune 你看看 Server 端有没有什么错误日志；另外，你也可以调用 https://github.com/caryyu/maxsubtitle-openapi-server 的 API 单步调试看看；对于卸载，我有空测试一下。

**Comment by hisune** [comment]
错误日志:System.Net.Http.HttpRequestException: Connection refused (localhost:3000)

卸载的话，我通过直接ssh到服务器删除了plugins对应的插件文件夹解决了

**Comment by hisune** [comment]
貌似你这个插件是不支持linux的？我看是dll的文件

**Comment by caryyu** [comment]
@hisune 现在 .NET 支持跨平台了。

**Comment by hisune** [comment]
@caryyu 
那上面提到的这个错误：
> 错误日志:System.Net.Http.HttpRequestException: Connection refused (localhost:3000)

应该是系统兼容问题？我是在qnap上的jellyfin，底层linux

还是我需要额外再起一个这个服务？https://github.com/caryyu/maxsubtitle-openapi-server

**Comment by caryyu** [comment]
@hisune 你需要额外再起 Server 端的服务的，该插件需要依赖该项目提供的 API。
